robot_hardware:
  - joint_hw
joint_hw:
  type: motion_control/JointHW
joint_position_controller:
  type: position_controllers/JointGroupPositionController
joint_state_controller:
  type: joint_state_controller/JointStateController
servo_pwm_controller:
  type: motion_control/ServoPWMController
  enable_servo: false